// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrrokwdxfawgltemjtdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJycm9rd2R4ZmF3Z2x0ZW1qdGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODg5MDAsImV4cCI6MjA2NDc2NDkwMH0.SQ0FQthsjoZh5-m-Tt9toefj5062AxazvmNq5iqhKjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);